### ISSUE TITLE
[Firefox] Scroll Offset Makes Selection Difficult

### ISSUE THREAD

**Issue by sagalbot** [tailwindcss/docs#158]
Hi Adam,

I've noticed an issue in Firefox when attempting to select the content of a `<pre>` when there is an `h2` or `h3` immediately afterwards. It makes it pretty challenging to copy and paste out of the code samples.

![Apr-09-2019 12-04-28](https://user-images.githubusercontent.com/692538/55827730-b7c67200-5abf-11e9-8cf6-5b4ac26fbd53.gif)

The selection would include the heading below, even though I'm nowhere near it. After digging in, this started to make sense:

![Screen Shot 2019-04-09 at 11 46 53 AM](https://user-images.githubusercontent.com/692538/55827802-e7757a00-5abf-11e9-9155-8137c9021c91.png)

I've narrowed it down to this chunk of less:

```css
  // Ridiculous scroll offset trash
  > h2::before, > h3::before {
    display: block;
    height: 6rem;
    margin-top: -6rem;
    visibility: hidden;
    content: "";
  }
```

I tried hacking this a number of ways, but didn't have much luck in resolving the issue. I thought maybe `user-select: none;` might solve it, but no dice.

It's still possible to make the selection, it just requires a lot of precision. I was thinking it might be simplest to have a 'copy to clipboard' button as a potential workaround. Let me know if you think this is worth pursuing.
